/**
 * Task Types
 *
 * Defines task structures for agent execution.
 * Used by AutoPattern for pattern selection and task orchestration.
 * Maps to AC-3.5 (AutoPattern)
 */

/**
 * Task priority levels
 */
export enum TaskPriority {
  /** Critical priority */
  CRITICAL = 'critical',
  /** High priority */
  HIGH = 'high',
  /** Normal priority */
  NORMAL = 'normal',
  /** Low priority */
  LOW = 'low',
}

/**
 * Task status
 */
export enum TaskStatus {
  /** Task is pending execution */
  PENDING = 'pending',
  /** Task is currently executing */
  IN_PROGRESS = 'in_progress',
  /** Task is blocked/waiting */
  BLOCKED = 'blocked',
  /** Task completed successfully */
  COMPLETED = 'completed',
  /** Task failed */
  FAILED = 'failed',
  /** Task was cancelled */
  CANCELLED = 'cancelled',
  /** Task requires human approval */
  AWAITING_APPROVAL = 'awaiting_approval',
}

/**
 * Task complexity assessment
 * Used by AutoPattern for pattern selection
 */
export interface TaskComplexity {
  /** Overall complexity score (0-10) */
  score: number;
  /** Number of required agents */
  agentCount: number;
  /** Estimated execution time (minutes) */
  estimatedDuration: number;
  /** Whether task can be parallelized */
  isParallelizable: boolean;
  /** Number of dependencies */
  dependencyCount: number;
  /** Number of subtasks */
  subtaskCount: number;
}

/**
 * Task dependency relationship
 */
export interface TaskDependency {
  /** ID of the dependent task */
  taskId: string;
  /** Type of dependency */
  type: 'blocks' | 'requires' | 'follows';
  /** Whether this is a hard or soft dependency */
  isCritical: boolean;
}

/**
 * Task result
 */
export interface TaskResult {
  /** Task ID */
  taskId: string;
  /** Whether task succeeded */
  success: boolean;
  /** Result data */
  data?: unknown;
  /** Error information if failed */
  error?: Error;
  /** Execution duration (milliseconds) */
  duration: number;
  /** Timestamp of completion */
  completedAt: Date;
  /** Agent that executed the task */
  executedBy: string;
}

/**
 * Core Task interface
 *
 * Represents a unit of work to be executed by agents.
 * Maps to AC-3.5 (AutoPattern) for pattern selection.
 */
export interface Task {
  /** Unique task identifier */
  id: string;
  /** Task title/name */
  name: string;
  /** Detailed task description */
  description: string;
  /** Task priority */
  priority: TaskPriority;
  /** Current task status */
  status: TaskStatus;
  /** Required capabilities for task execution */
  requiredCapabilities: string[];
  /** List of agent IDs assigned to this task */
  assignedAgents: string[];
  /** Task dependencies */
  dependencies: TaskDependency[];
  /** Subtasks (for nested/hierarchical patterns) */
  subtasks: Task[];
  /** Whether task requires human approval - Maps to AC-3.6 */
  requiresHumanApproval: boolean;
  /** Task complexity assessment */
  complexity?: TaskComplexity;
  /** Task creation timestamp */
  createdAt: Date;
  /** Task start timestamp */
  startedAt?: Date;
  /** Task completion timestamp */
  completedAt?: Date;
  /** Task result (if completed) */
  result?: TaskResult;
  /** Task timeout (milliseconds) */
  timeout?: number;
  /** Task metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Task execution plan
 * Generated by PatternSelector based on task analysis
 */
export interface TaskExecutionPlan {
  /** Recommended orchestration pattern */
  recommendedPattern: string;
  /** Reason for pattern selection */
  reason: string;
  /** Estimated execution order */
  executionOrder: string[];
  /** Parallel execution groups (if applicable) */
  parallelGroups?: string[][];
  /** Required agents */
  requiredAgents: string[];
  /** Estimated total duration (minutes) */
  estimatedDuration: number;
  /** Risk assessment */
  risks?: string[];
}

/**
 * Task template for common task patterns
 */
export interface TaskTemplate {
  /** Template identifier */
  id: string;
  /** Template name */
  name: string;
  /** Template description */
  description: string;
  /** Default priority */
  defaultPriority: TaskPriority;
  /** Required capabilities */
  requiredCapabilities: string[];
  /** Recommended pattern */
  recommendedPattern: string;
  /** Template metadata */
  metadata?: Record<string, unknown>;
}
