/**
 * Proposal Generator
 * Generates change proposal documents (proposal.md)
 * @module @musuhi/change-workflow
 */

import type { ChangeProposal } from './types.js';

/**
 * Proposal sections configuration
 */
export interface ProposalSections {
  /** Summary section content */
  summary?: string;

  /** Motivation section content */
  motivation?: string;

  /** Design overview section content */
  design?: string;

  /** Testing strategy section content */
  testing?: string;

  /** Deployment plan section content */
  deployment?: string;

  /** Rollback plan section content */
  rollback?: string;

  /** Related Articles (Constitutional) */
  relatedArticles?: number[];

  /** Additional custom sections */
  customSections?: Record<string, string>;
}

/**
 * Generated proposal document
 */
export interface GeneratedProposal {
  /** Proposal metadata */
  metadata: ChangeProposal;

  /** Proposal content (Markdown) */
  content: string;

  /** File path where proposal should be saved */
  filePath?: string;
}

/**
 * Proposal Generator
 * Generates structured change proposal documents
 */
export class ProposalGenerator {
  /**
   * Generate proposal document from metadata and sections
   */
  generateProposal(
    metadata: ChangeProposal,
    sections: ProposalSections
  ): GeneratedProposal {
    const content = this.buildProposalContent(metadata, sections);

    return {
      metadata,
      content,
    };
  }

  /**
   * Build proposal Markdown content
   */
  private buildProposalContent(
    metadata: ChangeProposal,
    sections: ProposalSections
  ): string {
    const lines: string[] = [];

    // Title and metadata header
    lines.push(`# Change Proposal: ${metadata.name}`);
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Metadata');
    lines.push('');
    lines.push(`- **Name**: ${metadata.name}`);
    lines.push(`- **Author**: ${metadata.author}`);
    lines.push(`- **Created**: ${metadata.createdDate}`);
    lines.push(`- **Status**: ${this.getStatusBadge(metadata.status)}`);
    lines.push('');

    // Related Constitutional Articles
    if (sections.relatedArticles && sections.relatedArticles.length > 0) {
      lines.push('## Related Constitutional Articles');
      lines.push('');
      sections.relatedArticles.forEach((articleNum) => {
        lines.push(`- Article ${articleNum}: ${this.getArticleTitle(articleNum)}`);
      });
      lines.push('');
    }

    // Summary
    lines.push('## Summary');
    lines.push('');
    if (sections.summary) {
      lines.push(sections.summary);
    } else {
      lines.push(metadata.description);
    }
    lines.push('');

    // Motivation
    if (sections.motivation) {
      lines.push('## Motivation');
      lines.push('');
      lines.push(sections.motivation);
      lines.push('');
    }

    // Design
    if (sections.design) {
      lines.push('## Design');
      lines.push('');
      lines.push(sections.design);
      lines.push('');
    }

    // Testing Strategy
    if (sections.testing) {
      lines.push('## Testing Strategy');
      lines.push('');
      lines.push(sections.testing);
      lines.push('');
    }

    // Deployment Plan
    if (sections.deployment) {
      lines.push('## Deployment Plan');
      lines.push('');
      lines.push(sections.deployment);
      lines.push('');
    }

    // Rollback Plan
    if (sections.rollback) {
      lines.push('## Rollback Plan');
      lines.push('');
      lines.push(sections.rollback);
      lines.push('');
    }

    // Custom sections
    if (sections.customSections) {
      Object.entries(sections.customSections).forEach(([title, content]) => {
        lines.push(`## ${title}`);
        lines.push('');
        lines.push(content);
        lines.push('');
      });
    }

    // Checklist
    lines.push('## Checklist');
    lines.push('');
    lines.push('- [ ] Design reviewed');
    lines.push('- [ ] Tests written');
    lines.push('- [ ] Documentation updated');
    lines.push('- [ ] Constitutional Articles compliance verified');
    lines.push('- [ ] Phase -1 Gate passed');
    lines.push('- [ ] Code review completed');
    lines.push('- [ ] Deployment plan validated');
    lines.push('- [ ] Rollback plan tested');
    lines.push('');

    // Footer
    lines.push('---');
    lines.push('');
    lines.push('*Generated by MUSUHI Change Workflow System*');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Get status badge for Markdown
   */
  private getStatusBadge(status: ChangeProposal['status']): string {
    const badges: Record<ChangeProposal['status'], string> = {
      draft: '🟡 Draft',
      review: '🔵 In Review',
      approved: '🟢 Approved',
      archived: '⚫ Archived',
    };

    return badges[status];
  }

  /**
   * Get Article title by number
   */
  private getArticleTitle(articleNum: number): string {
    const titles: Record<number, string> = {
      1: 'Library-First Development',
      2: 'Test-First Development',
      3: 'Security-First Development',
      4: 'Documentation-First Development',
      5: 'Simplicity-First Development',
      6: 'Performance-First Development',
      7: 'Accessibility-First Development',
      8: 'Privacy-First Development',
      9: 'Integration-First Development',
    };

    return titles[articleNum] || `Article ${articleNum}`;
  }

  /**
   * Parse proposal metadata from Markdown content
   */
  parseProposalMetadata(content: string): ChangeProposal | null {
    try {
      const nameMatch = content.match(/^#\s+Change Proposal:\s+(.+)$/m);
      const authorMatch = content.match(/\*\*Author\*\*:\s+(.+)$/m);
      const createdMatch = content.match(/\*\*Created\*\*:\s+(.+)$/m);
      const statusMatch = content.match(/\*\*Status\*\*:\s+[^\s]+\s+(.+)$/m);

      if (!nameMatch || !authorMatch || !createdMatch) {
        return null;
      }

      // Extract description from Summary section
      const summaryMatch = content.match(/##\s+Summary\s*\n\s*\n(.+?)(?=\n##|\n---|\n$)/s);
      const description = summaryMatch ? summaryMatch[1]?.trim() || '' : '';

      // Parse status
      let status: ChangeProposal['status'] = 'draft';
      if (statusMatch) {
        const statusText = statusMatch[1]?.toLowerCase() || '';
        if (statusText.includes('review')) status = 'review';
        else if (statusText.includes('approved')) status = 'approved';
        else if (statusText.includes('archived')) status = 'archived';
      }

      return {
        name: nameMatch[1]!.trim(),
        author: authorMatch[1]!.trim(),
        createdDate: createdMatch[1]!.trim(),
        description,
        status,
      };
    } catch {
      return null;
    }
  }

  /**
   * Update proposal status
   */
  updateProposalStatus(
    content: string,
    newStatus: ChangeProposal['status']
  ): string {
    const statusBadge = this.getStatusBadge(newStatus);
    return content.replace(
      /\*\*Status\*\*:\s+[^\n]+/,
      `**Status**: ${statusBadge}`
    );
  }

  /**
   * Extract related articles from proposal content
   */
  extractRelatedArticles(content: string): number[] {
    const articles: number[] = [];
    const articlePattern = /Article\s+(\d+)/gi;
    let match;

    while ((match = articlePattern.exec(content)) !== null) {
      const articleNum = parseInt(match[1]!, 10);
      if (articleNum >= 1 && articleNum <= 9 && !articles.includes(articleNum)) {
        articles.push(articleNum);
      }
    }

    return articles.sort((a, b) => a - b);
  }

  /**
   * Generate minimal proposal template
   */
  generateTemplate(metadata: ChangeProposal): GeneratedProposal {
    return this.generateProposal(metadata, {
      summary: metadata.description,
      motivation: '*TODO: Describe why this change is necessary*',
      design: '*TODO: Describe the technical design*',
      testing: '*TODO: Describe testing strategy*',
      deployment: '*TODO: Describe deployment steps*',
      rollback: '*TODO: Describe rollback procedure*',
    });
  }
}
